version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  node-express:
    build:
      context: ./node-express
    container_name: node-express
    working_dir: /usr/src/app
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/mydatabase
    depends_on:
      - postgres

  nextjs:
    build:
      context: ./nextjs
    container_name: nextjs
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - node-express

volumes:
  postgres-data:

